LOGIN #3 and #4 (KN-44 KN-70) Login Refactor
AbigailDawson/knownative pull request #164
Opened 2024-12-14 22:36 UTC by agrimes23

This includes the login modal and refactored login page (if user tries to access dashboard but is not logged in) according to the figma wireframes. I used @JPEscobari's FormInput component and worked with him to make it reusable between both signup and login. The login modal uses this component as well, and uses the reusable modal in ui-components/Modal.

Notes:
- Form Input errors for sign up only show when the user clicks away from the input and there is an error. Error does go away when the input is correct and the user clicks out of the input. This can be changed if another behavior is preferred.
- Made sure that input error messages do not move other elements when they appear. The exception being the password validation since it's a deliberate behavior according to the wireframes.
- Login Page and modal have styling for mobile, but login modal on mobile is a bit too long on mobile screens.

Some of @JPEscobari 's work with the signup is in this PR as well. Mainly updating the password validation. He will submit a PR for the rest of signup changes after this is merged with this user-auth branch!

2024-12-14 22:37 UTC, agrimes23 commented
Looks like there's a lot of commits, but this includes code updated from develop and main (some of main's code is not on develop, actually). Let me know if you'd like to discuss or would like for me to do something different

2025-01-14 06:48 UTC, psantos2107 requested changes
Hey Alex! This looks amazing! (and luckily no merge conflicts). I love the flow! If possible, can you or JP make sure that the sign-up form is also a pop up, just like the login form is?

2025-01-14 17:11 UTC, agrimes23 commented
@psantos2107 Just spoke with JP, and mentioned it would be easier to merge these login changes with user-auth first, and then he can work on the rest of the signup code tasks on a new branch. This PR is mainly for the login flow anyway, but does have some signup related code due to the reusable components between the two. Would it be okay to merge as is?

2025-01-14 19:48 UTC, merged

2025-01-16 04:02 UTC, JPEscobari commented
The Signup modal is done!

I’ve sent a pull request to `user-authentication-authorization` that should be an easy merge.